language: ruby
cache:
  - bundler
  - yarn
services:
  - postgresql
before_install:
  - nvm install --lts
before_script:
  - set :bundle_flags, '--quiet'
  - bundle install --jobs=3 --retry=3
  - bundle config --local deployment 'true'
  - yarn
  - bundle exec rake db:create
  - bundle exec rake db:schema:load
script:
  - bundle exec rspec